### ISSUE TITLE
Error when trying to load data using spot_inspector plugin

### ISSUE THREAD

**Issue by sebgoti** [TissUUmaps/TissUUmaps#22]
I downloaded Tissuumaps on Mac (not sure if the plugins are actually working for this OS), and tried to load an ISS experiment using the `spot_inspector` plugin following the [video tutorial](https://tissuumaps.github.io/tutorials/#spot_inspector) for the plugin. I open an image and then try to load the rest of the experiment, however, nothing happens and get the following message on the terminal:
```
ERROR:tissuumaps:Exception on /plugins/Spot_Inspector/importFolder [POST]
Traceback (most recent call last):
  File "/Users/segonzal/opt/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/segonzal/opt/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/segonzal/opt/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/segonzal/opt/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/segonzal/opt/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/tissuumaps/views.py", line 948, in pluginJS
    return pluginMethod(content)
  File "/Users/segonzal/.tissuumaps/plugins/Spot_Inspector.py", line 301, in importFolder
    relativepath = unquote(jsonParam["path"])
NameError: name 'unquote' is not defined
```

**Comment by cavenel** [comment]
Hi @sebgoti,
This probably means that matplotlib is not installed in the Python version running TissUUmaps.
Could you try running:
`pip install matplotlib pillow`
before starting TissUUmaps?
I will update the plugin to make the error more understandable!

**Comment by sebgoti** [comment]
Now it works, thank you! Another question, I am trying to visualise an ISS experiment where we do the detection of the spots on an anchor image. How could one add this additional image on top of the R*_C* stack and then use the `spot_inspector`? So far when I open the anchor it overwrites the rest of the experiment.

**Comment by cavenel** [comment]
If you are using TissUUmaps from the GUI, and all images are in the same folder, then drag and drop of the image should add it as a new layer and not replace all layers. Unfortunately, right now the plugin will fail if an image doesn't follow the R*_C* notation.
One way would be to name your anchor R0_C5.tif?

**Comment by cavenel** [comment]
I will close this issue as the initial problem has been fixed.
