### ISSUE TITLE
Package downgrade required - possible to specify in environment file?

### ISSUE THREAD

**Issue by phiwei** [TissUUmaps/TissUUmaps#37]
Hi, 

I followed the installation steps on the documentation page for a server with Ubuntu 20.04. For the TissUUmaps server to start running, I had to downgrade the following packages:

- hdf5 to 1.12.2
- Werkzeug to 2.2.2
- Flask to 2.1.3

I am not sure if I made some mistake in the setup and this caused these issues, but I think that is not likely since I just followed the steps in the documentation. Potentially it would be good to provide an environment file with specific package versions specified? If this already exists, please point me to where I can find it!

Thanks!
Best wishes
Philippe

**Comment by cavenel** [comment]
Hi @phiwei,

We are about to release v3.2, and I will make sure it works with the latest version of all packages. But I agree with you we need to put working versions in the environment file.

**Comment by cavenel** [comment]
I was able to reproduce the issue with flask (flask keeps deprecating / removing things, it will be fixed in the next release).
But I could not see the issues with Werkzeug (I have version 3.0.0), could you show us the errors?

For hdf5, I think as long as h5py is compiled with the same version as the conda version, it should work. Might have to reinstall it with the correct version from pip. I will double check.

**Comment by npielawski** [comment]
I got the same issue with Werkzeug, here are the logs:
```
Traceback (most recent call last):
 File "/opt/homebrew/anaconda3/envs/tissuumaps_env/bin/tissuumaps", line 5, in <module>
  from tissuumaps.gui import main
 File "/opt/homebrew/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/tissuumaps/__init__.py", line 26, in <module>
  from flask import Flask
 File "/opt/homebrew/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
  from .app import Flask as Flask
 File "/opt/homebrew/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/app.py", line 27, in <module>
  from . import cli
 File "/opt/homebrew/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/cli.py", line 17, in <module>
  from .helpers import get_debug_flag
 File "/opt/homebrew/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/flask/helpers.py", line 14, in <module>
  from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/opt/homebrew/anaconda3/envs/tissuumaps_env/lib/python3.9/site-packages/werkzeug/urls.py)
```

**Comment by munizmom** [comment]
Dear all, in case it helps. For M1/M2 users . The only extra step to install TissUUmaps v3.1.1.6 in condo  is down version Flask from 3.0.0 to 3.2.2. These are the instructions  and order that worked for me: 

conda create -y -n tissuumaps_env -c conda-forge python=3.9
conda activate tissuumaps_env
conda install -c conda-forge libvips pyvips openslide-python
pip install "TissUUmaps[full]"
pip install flask==2.0.0 #downgrade from flask 3.0.0 to 2.3.3 or there is an error opening tissuumaps linked to Flask
