### ISSUE TITLE
Not starting on macOS Sonoma 14.4.1 M1 Pro

### ISSUE THREAD

**Issue by gaojinglin99** [TissUUmaps/TissUUmaps#58]
I've tried installing all the latest releases on macOS Sonoma on an M1 Pro and none of them open (including the release that supports both `arm64` and `x86_64`).

I've done succesfully installed vips via `brew install vips`.

I move the installation to the `Application` folder, open it, wait until it verifies and then try to open it again with `right-click` and then `Open`, and it takes some seconds but it doesn't open (I assume it crashes).

Has anyone managed to make it work on macOS Sonoma for `arm64`?

This is my neofetch:
```
                    'c.          jinglin@Jinglins-Mac 
                 ,xNMM.          -------------------- 
               .OMMMMo           OS: macOS 14.4.1 23E224 arm64 
               OMMM0,            Host: MacBookPro18,3 
     .;loddo:' loolloddol;.      Kernel: 23.4.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 21 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 118 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2560x1440 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Red (Light) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: Apple_Terminal 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: SFMono-Regular 
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1 Pro 
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1 Pro 
       .cooc,.    .,coo:.        Memory: 2079MiB / 16384MiB 

```

**Comment by Artur-man** [comment]
I have the same problem actually. 

The dmg file for the app is not working for me. The app doesnt start as also stated by @gaojinglin99.
https://github.com/TissUUmaps/TissUUmaps/releases/tag

However, I can still build from pip as instructed below, and that works
https://tissuumaps.github.io/installation/
https://pypi.org/project/TissUUmaps/

Here is also my neofetch:

```
                    'c.          amanuky@LANDTHALER57 
                 ,xNMM.          -------------------- 
               .OMMMMo           OS: macOS 12.5.1 21G83 arm64 
               OMMM0,            Host: MacBookPro18,2 
     .;loddo:' loolloddol;.      Kernel: 21.6.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 14 days, 4 hours, 26 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 189 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: bash 3.2.57 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3840x1620 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: Apple_Terminal 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: SFMono-Regular 
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1 Max 
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1 Max 
       .cooc,.    .,coo:.        Memory: 9307MiB / 65536MiB 
```

**Comment by Artur-man** [comment]
I have recently tested this again on the latest release, are there any plans to fix it ? I normally open this from a conda environment but I would rather use the application directly :D

**Comment by cavenel** [comment]
Hi,
I finally had the time to do some testing with GitHub actions and MacOS 14 arm64.
I had to add manually the DYLD_FALLBACK_LIBRARY_PATH environment variable to search into /opt/homebrew/lib to fix https://github.com/Homebrew/brew/issues/13481. It is a quite ugly hack, but it should work for now.

Can you test with the latest release ([3.2.1.10](https://github.com/TissUUmaps/TissUUmaps/releases/tag/3.2.1.10))?

**Comment by Artur-man** [comment]
Dear @cavenel, I have quickly checked it on my MacOS 12.5.1 arm64. I think the problem persist, to be clear I have added DYLD_FALLBACK_LIBRARY_PATH to my .bash_profile 

```
export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
```

This doesn't open though, but I am positive to investigate this with anybody further.

**Comment by cavenel** [comment]
Thanks for the quick answer.

Unfortunately, I was only able to build for MacOS 14, and I don't think you can run it on an oldest version.
I can check if there is a way to force compatibility.

**Comment by Artur-man** [comment]
Thanks, I have quickly checked, am I getting a `numpy` error ???!?

```
INFO:root: * TissUUmaps version: 3.2.1.10
Traceback (most recent call last):
  File "numpy/_core/__init__.py", line 23, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/_core/multiarray.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/_core/overrides.py", line 8, in <module>
ImportError: dlopen(/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so, 0x0002): Symbol not found: (_cblas_caxpy$NEWLAPACK$ILP64)
  Referenced from: '/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so'
  Expected in: '/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numpy/__init__.py", line 114, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/__config__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/_core/__init__.py", line 49, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/Applications/TissUUmaps.app/Contents/MacOS/TissUUmaps"
  * The NumPy version is: "2.1.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so, 0x0002): Symbol not found: (_cblas_caxpy$NEWLAPACK$ILP64)
  Referenced from: '/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so'
  Expected in: '/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tissuumaps/gui.py", line 58, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tissuumaps/__init__.py", line 112, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tissuumaps/views.py", line 55, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tissuumaps/read_h5ad.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "h5py/__init__.py", line 33, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "h5py/version.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/__init__.py", line 119, in <module>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
[85979] Failed to execute script 'gui' due to unhandled exception: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
[85979] Traceback:
Traceback (most recent call last):
  File "numpy/_core/__init__.py", line 23, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/_core/multiarray.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/_core/overrides.py", line 8, in <module>
ImportError: dlopen(/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so, 0x0002): Symbol not found: (_cblas_caxpy$NEWLAPACK$ILP64)
  Referenced from: '/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so'
  Expected in: '/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numpy/__init__.py", line 114, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/__config__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/_core/__init__.py", line 49, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/Applications/TissUUmaps.app/Contents/MacOS/TissUUmaps"
  * The NumPy version is: "2.1.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so, 0x0002): Symbol not found: (_cblas_caxpy$NEWLAPACK$ILP64)
  Referenced from: '/Applications/TissUUmaps.app/Contents/MacOS/numpy/_core/_multiarray_umath.cpython-311-darwin.so'
  Expected in: '/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tissuumaps/gui.py", line 58, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tissuumaps/__init__.py", line 112, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tissuumaps/views.py", line 55, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tissuumaps/read_h5ad.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "h5py/__init__.py", line 33, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "h5py/version.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "numpy/__init__.py", line 119, in <module>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by cavenel** [comment]
This seems to be related to your version of Accelerate, as described here https://github.com/numpy/numpy/issues/25026
Unfortunately the only answer I see in the thread and linked threads is "update your os to >13.5".
Not sure I can help much with this issue :(

**Comment by Artur-man** [comment]
ah thanks Christophe, I will switch to 13-14 then, no worries :D
