### ISSUE TITLE
Numpy version issue

### ISSUE THREAD

**Issue by smith6jt-cop** [TissUUmaps/TissUUmaps#66]
Just wanted to document an issue that may or may not be related to a problem sharing via static webpage.  Running in fresh conda environment, Windows 10, pip installed pyvips, openslide and TissUUmaps[full], downloaded libvips 8.15.3 binaries and added to path.  After creating the static webpage files, the index.html opens a tissuumaps page in Chrome, but there is no data.

(tissuumaps_env) c:\Users\smith6jt>tissuumaps
INFO:root: * TissUUmaps version: 3.2.1.9

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\smith6jt\AppData\Local\miniconda3\envs\tissuumaps_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\smith6jt\AppData\Local\miniconda3\envs\tissuumaps_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\smith6jt\AppData\Local\miniconda3\envs\tissuumaps_env\Scripts\tissuumaps.exe\__main__.py", line 4, in <module>
    from tissuumaps.gui import main
  File "C:\Users\smith6jt\AppData\Local\miniconda3\envs\tissuumaps_env\lib\site-packages\tissuumaps\gui.py", line 21, in <module>
    from PySide6 import QtGui
  File "C:\Users\smith6jt\AppData\Local\miniconda3\envs\tissuumaps_env\lib\site-packages\PySide6\__init__.py", line 124, in <module>
    _setupQtDirectories()
  File "C:\Users\smith6jt\AppData\Local\miniconda3\envs\tissuumaps_env\lib\site-packages\PySide6\__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "C:\Users\smith6jt\AppData\Local\miniconda3\envs\tissuumaps_env\lib\site-packages\shiboken6\__init__.py", line 27, in <module>
    from shiboken6.Shiboken import *

**Comment by smith6jt-cop** [comment]
Hello,

Thank you for your help.  I followed your instructions which worked as expected.  I also managed to run the static export on an Apache server; however, my goal is to be able to share data with collaborators.  Perhaps I am missing or not understanding the procedure to accomplish this.  Please advise.

Thank you,

Justin

**Comment by cavenel** [comment]
I'm closing for now as the sharing seems like a different issue.
For sharing, you can have a look at our documentation: [Sharing projects
](https://tissuumaps.github.io/TissUUmaps-docs/docs/sharing/index.html)

Christophe
